Fix shuttles
Persistent-SS13/Persistent-Bay pull request #1021
Opened 2018-11-05 19:08 UTC by Chryseus

Fixes shuttle creation and flight.

2018-11-07 17:56 UTC, michaelchessall requested changes

2018-11-07 17:56 UTC, FaurnsGoldberg commented on code/modules/shuttles/shuttle.dm
> +				if(istype(TA, ceiling_type) || istype(TA, /turf/simulated/floor/airless) || istype(TA, /turf/simulated/open))
This section is problematic as heck. I'm worried about shuttles landing underneath constructed areas and tearing them apart when they leave. This also deletes the contents of the shuttles roof, which is not a good idea, in any circumstance.

2018-11-08 21:59 UTC, Chryseus commented on code/modules/shuttles/shuttle.dm
> +				if(istype(TA, ceiling_type) || istype(TA, /turf/simulated/floor/airless) || istype(TA, /turf/simulated/open))
You're right, I'll update it so it works properly in all situations.

2018-11-18 16:51 UTC, Chryseus commented on code/modules/shuttles/shuttle.dm
> +				if(istype(TA, ceiling_type) || istype(TA, /turf/simulated/floor/airless) || istype(TA, /turf/simulated/open))
I'm quite happy with how the shuttles work now, docks have a new variable for interior or exterior which should be saved, items left on the roof are now also kept, although it might make more sense for them to be knocked away when the shuttle moves.

2018-11-23 14:02 UTC, Chryseus commented
**Current major issues remaining**

- External docks need to check for non-space areas above to avoid causing damage.
- Have docking beacons reset properly when moved

**Features being worked on for a later PR**
- Allow arbitrary shuttle sizes (within reason)
- Rotation of shuttles
- Fuel consumption, internal / external fuel port, etc

2018-11-24 20:03 UTC, Chryseus commented
PR is ready for review again.
Extensive testing has been done and I can't get it to break so that's a good sign at least.

2018-11-26 05:21 UTC, michaelchessall approved these changes

2018-11-26 05:22 UTC, merged