Morefixesnexus
Persistent-SS13/Persistent-Bay pull request #1120
Opened 2019-03-31 23:56 UTC by PsyCommando

This should fix the damage issues on the motorbike. Also makes some changes to make some of the machine code I modified make more sense. Fixed a few graphic glitches with noticeboards and etc.

2019-04-01 09:49 UTC, ingles98 requested changes
Most stuff is some sh*ti dont understand cuz im dumdum.
There are serious missing character issues however which you wanna look into.

2019-04-01 09:49 UTC, ingles98 commented on code/__defines/damage_organs.dm
> -#define ORGAN_ASSISTED 1
Why was this removed?

2019-04-01 09:49 UTC, ingles98 commented on code/__defines/materials.dm
> -#define MATERIAL_WOOD						"wood"
Also this

2019-04-01 09:49 UTC, ingles98 commented on code/_helpers/icons.dm
> +	(Rotating red by 60� produces yellow.) The result is another HSV or HSVA color with the same saturation and value
Well i hope anyone who reads it knows that it is degrees. Shouldn't be a problem, but id be worried if this was happening on my strings

2019-04-01 09:49 UTC, ingles98 commented on code/_helpers/icons.dm
> +proc/getFlatIcon(image/A, defdir=2, deficon=null, defstate="", defblend=BLEND_DEFAULT, always_use_defdir = 0)
Wait, what does thus PR have to do with the icon flattening? Just tell me so i know what might have been wrong with it

2019-04-01 09:49 UTC, ingles98 commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
Why was this removed? Again not described in the PR. Not sure of the extent of this tho

2019-04-01 09:49 UTC, ingles98 commented on code/datums/datum.dm
> -/datum/VV_static()
Why was this removed?

2019-04-01 09:49 UTC, ingles98 commented on code/game/machinery/atmoalter/area_atmos_computer.dm
> +		if(scrubber.isactive())
Why tho. Seems prettier anyways

2019-04-01 09:49 UTC, ingles98 commented on code/game/objects/items/weapons/tools/welder.dm
> +	var/obj/item/weapon/welder_tank/tank = new /obj/item/weapon/welder_tank() // where the fuel is stored
Shouldnt we actually put that on New()?

2019-04-01 09:49 UTC, ingles98 commented on code/game/objects/structures/wall_items/mirror.dm
>  /obj/structure/mirror
A lot of changes around the mirror which i believe should be noted more thoroughly on the PR

2019-04-01 09:49 UTC, ingles98 commented on code/modules/flufftext/TextFilters.dm
> +						newletter = pick("�", "�", "%", "�", "�")
Oooof...

2019-04-01 09:49 UTC, ingles98 commented on code/modules/flufftext/TextFilters.dm
> +					newletter = "�w��b�%> -BZZT-"
Moar oofs

2019-04-01 09:49 UTC, ingles98 commented on code/modules/flufftext/TextFilters.dm
> +						newletter = "�"
Dont forget these

2019-04-01 09:49 UTC, ingles98 commented on code/modules/hydroponics/trays/tray.dm
> -	if(seed.mutants. && seed.mutants.len && severity > 1)
HOW and WHY did this even compile in the first place

2019-04-01 09:49 UTC, ingles98 commented on code/modules/mob/mob.dm
> +	if(ability_master)
Oh i see it was moved into here

2019-04-01 09:49 UTC, ingles98 commented on code/modules/multiz/_stubs.dm
> -HasAbove(var/z)
Why were these removed ?

2019-04-01 09:49 UTC, ingles98 commented on persistentss13.dme
> -#include "code\game\objects\items\weapons\tools\welders\weldertank.dm"
what

2019-04-01 09:49 UTC, ingles98 commented on persistentss13.dme
> +#define FILE_DIR "code"
What are all these ?

2019-04-01 13:12 UTC, PsyCommando commented on code/modules/hydroponics/trays/tray.dm
> -	if(seed.mutants. && seed.mutants.len && severity > 1)
I don't know man. I found like 10 million typos like that which DM somehow compiles fine with, and I've been fixing them.

2019-04-01 13:12 UTC, PsyCommando commented on code/modules/multiz/_stubs.dm
> -HasAbove(var/z)
Because it shouldn't even compile.

2019-04-01 13:13 UTC, PsyCommando commented on persistentss13.dme
> -#include "code\game\objects\items\weapons\tools\welders\weldertank.dm"
Empty file, check the diff

2019-04-01 13:13 UTC, PsyCommando commented on persistentss13.dme
> +#define FILE_DIR "code"
Autogenerated dme stuff I guess

2019-04-01 13:16 UTC, PsyCommando commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
It was moved around, because its part of the mob class, and it makes little sense for it to be in the "ability_screen_object.dm" file. The way byond allows you to redefine the same proc multiple times makes this reaally bad when you're trying to find bugs or modify code, and its likely the compiler won't even say anything if someone write something stupid.

2019-04-01 13:16 UTC, ingles98 commented on code/modules/hydroponics/trays/tray.dm
> -	if(seed.mutants. && seed.mutants.len && severity > 1)
Could be because the dot operator is returning a value? Not sure if it is returning the actual true value tho, but would explain as to why it compiles, while possibly having some weird behaviours ingame

2019-04-01 13:17 UTC, PsyCommando commented on code/_helpers/icons.dm
> +proc/getFlatIcon(image/A, defdir=2, deficon=null, defstate="", defblend=BLEND_DEFAULT, always_use_defdir = 0)
Check the diff. Only thing it did it reformat the proc within our code conventions.

2019-04-01 13:17 UTC, ingles98 commented on code/modules/hydroponics/trays/tray.dm
> -	if(seed.mutants. && seed.mutants.len && severity > 1)
Good find nevertheless

2019-04-01 13:17 UTC, PsyCommando commented on code/_helpers/icons.dm
> +	(Rotating red by 60� produces yellow.) The result is another HSV or HSVA color with the same saturation and value
Might be some unicode bs.

2019-04-01 13:18 UTC, PsyCommando commented on code/__defines/materials.dm
> -#define MATERIAL_WOOD						"wood"
Its defined in double, which is very very bad

2019-04-01 13:18 UTC, ingles98 commented on persistentss13.dme
> -#include "code\game\objects\items\weapons\tools\welders\weldertank.dm"
Yeah very weird, because there is an actual welder tank

2019-04-01 13:18 UTC, ingles98 commented on persistentss13.dme
> +#define FILE_DIR "code"
Ah oke. Probably from the new update im guessing

2019-04-01 13:19 UTC, PsyCommando commented on code/__defines/damage_organs.dm
> -#define ORGAN_ASSISTED 1
Because organs use status flags now, and this was a double define of a status flag, which is really bad.

2019-04-01 13:19 UTC, ingles98 commented on code/modules/multiz/_stubs.dm
> -HasAbove(var/z)
So they werent even used? Nice

2019-04-01 13:20 UTC, PsyCommando commented on code/datums/datum.dm
> -/datum/VV_static()
Because its content was merged with another redundant definition of this proc

2019-04-01 13:23 UTC, ingles98 commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
Indeed, i saw the change and understood it after going through it all

2019-04-01 13:23 UTC, PsyCommando commented on code/game/machinery/atmoalter/area_atmos_computer.dm
> +		if(scrubber.isactive())
Because there's a difference between simply being on or active. Right now machines can be in the off, idle, or active power state. It was ambiguous that "ison" would return true only when it was in active state and not idle state. So I changed ison to return truee when !isoff istead, and added isactive to get whether the machine is in active state, since ison was no longer associated with that state. Its a lot more intuitive this way.

2019-04-01 13:24 UTC, ingles98 commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
There is, however, some stuff like hooks which are more helpful being at the source file than what it is hooked into. I do agree it can complicate things indeed

2019-04-01 13:26 UTC, PsyCommando commented on code/game/objects/items/weapons/tools/welder.dm
> +	var/obj/item/weapon/welder_tank/tank = new /obj/item/weapon/welder_tank() // where the fuel is stored
More or less. Normally it creates the path in there when needed but I noticed some weirdness because some things try to access the tank directly as an object. So, its better for now. I'll most likely make more changes to it later on anyways.

2019-04-01 13:28 UTC, PsyCommando commented on code/game/objects/structures/wall_items/mirror.dm
>  /obj/structure/mirror
Only thing it does is make its icon properly offset. Which I mentionned in the notes. Also, you're not exactly preaching to the right person on the repo. Both nata and brawler tend to have less details on their pr than me..

2019-04-01 13:48 UTC, ingles98 commented on code/game/objects/structures/wall_items/mirror.dm
>  /obj/structure/mirror
I know. Thing is i didnt review theirs. I dont want to offend, on the opposite seriously. Also there is no point in reviewing their after they got merged, but youre absolutely right, and brawlers knows what i think. Most of my review is attempting to understand certain changes, and also note stuff that maybe you have missed

2019-04-01 13:51 UTC, ingles98 commented on code/_helpers/icons.dm
> +	(Rotating red by 60� produces yellow.) The result is another HSV or HSVA color with the same saturation and value
Maybe the filesystem or your editor idk

2019-04-01 13:52 UTC, ingles98 commented on code/_helpers/icons.dm
> +proc/getFlatIcon(image/A, defdir=2, deficon=null, defstate="", defblend=BLEND_DEFAULT, always_use_defdir = 0)
Aight. I didnt manage to see it all cause diff does this thinf of chopping all the parts making it look like many changes. I see the code is the same

2019-04-01 14:44 UTC, PsyCommando commented on code/_helpers/icons.dm
> +	(Rotating red by 60� produces yellow.) The result is another HSV or HSVA color with the same saturation and value
Its just that DM can't handle utf8. And someone used extended ascii characters that aren't in utf8.

2019-04-01 14:49 UTC, PsyCommando commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
Its not really a good idea to do that at all. The way the compiler deals with it, it can do anything from defining a brand new class if the names don't match anymore, to compiling the procs in the wrong order. That's how weird random uuntraceable issues start appearing.

2019-04-01 14:53 UTC, PsyCommando commented on code/game/objects/structures/wall_items/mirror.dm
>  /obj/structure/mirror
Yeah, that's fine. Its just the whole thing about documenting my prs. When people don't even read the change list and most pr just get merged immediately its kinda hard to care about documenting things in-depth

2019-04-01 14:54 UTC, PsyCommando commented on code/modules/hydroponics/trays/tray.dm
> -	if(seed.mutants. && seed.mutants.len && severity > 1)
Nah, I've seen even worst things that still compiled. I think the DM parser is kinda fucked under some circumstances.

2019-04-01 14:56 UTC, PsyCommando commented on code/modules/multiz/_stubs.dm
> -HasAbove(var/z)
Nah, its just this isn't a definition or a proc call. So its hard to tell wtf the compiler even does with those.

2019-04-01 14:56 UTC, PsyCommando commented on persistentss13.dme
> -#include "code\game\objects\items\weapons\tools\welders\weldertank.dm"
They were all moved to separate files, but the old empty file was leftover.

2019-04-01 15:10 UTC, ingles98 commented on code/_onclick/hud/ability_screen_objects.dm
> -		ability_master.update_spells(0)
That is true, what i meant by the hooks was that you usually dont use a proc that already exists

2019-04-01 15:11 UTC, ingles98 commented on code/game/objects/structures/wall_items/mirror.dm
>  /obj/structure/mirror
Well i understand. But we really should document detailed, even more so with actual comments in the code... Ss13 is full of ages old undocummented wizardry

2019-04-01 17:38 UTC, ingles98 approved these changes

2019-04-02 22:37 UTC, Andrew-Fall commented
Going to pull this then fix the errors

2019-04-02 22:37 UTC, merged