General fixes
Persistent-SS13/Persistent-Bay pull request #1127
Opened 2019-04-02 23:42 UTC by Andrew-Fall

2019-04-03 03:39 UTC, PsyCommando requested changes
Just a few things I noted.

2019-04-03 03:39 UTC, PsyCommando commented on code/game/antagonist/alien/borer.dm
> +				if(head && !(head.status & ORGAN_ROBOTIC))
There's actually a macro for this BP_IS_ROBOTIC() Its what bay does and its more flexible than always doing the flag check

2019-04-03 03:39 UTC, PsyCommando commented on code/datums/extensions/extensions.dm
> +				log_debug(" /datum/after_load(): found a list extension.. Not setting holder.")
Why are you adding a single white space in all those files?

2019-04-03 03:39 UTC, PsyCommando commented on maps/nexus/nexus_empty.dmm
> +"b" = (/turf/unsimulated/wall,/area/space)
Isn't that meant to be an empty map?

2019-04-03 11:17 UTC, ingles98 commented on code/datums/extensions/extensions.dm
> +				log_debug(" /datum/after_load(): found a list extension.. Not setting holder.")
Looks automated, idk what could be the reason tbh

2019-04-03 11:59 UTC, Andrew-Fall commented on code/datums/extensions/extensions.dm
> +				log_debug(" /datum/after_load(): found a list extension.. Not setting holder.")
Because Travis identifies those as text datum paths. Adding the space prevents that. Usually it indicates a text2path

2019-04-03 12:00 UTC, Andrew-Fall commented on maps/nexus/nexus_empty.dmm
> +"b" = (/turf/unsimulated/wall,/area/space)
Yes minus admin z which doesn't save and is used for unit tests

2019-04-03 12:22 UTC, Andrew-Fall commented on code/game/antagonist/alien/borer.dm
> +				if(head && !(head.status & ORGAN_ROBOTIC))
Ugh, I'll update them then.

2019-04-04 16:49 UTC, ingles98 approved these changes

2019-04-04 16:49 UTC, ingles98 commented on code/modules/flufftext/TextFilters.dm
> +						newletter = pick("ø", "Ð", "%", "æ", "µ")
Not entirely sure about what is going on with these but seem harmless enough

2019-04-04 16:49 UTC, ingles98 commented on code/modules/mob/living/carbon/human/species/station/nabber.dm
> +				if(partstatus & ORGAN_ROBOTIC)
Oof i believe this is supposed to be part.status am i right?

2019-04-04 22:51 UTC, Andrew-Fall commented on code/modules/mob/living/carbon/human/species/station/nabber.dm
> +				if(partstatus & ORGAN_ROBOTIC)
Yep, that file isn't included in the build hence me missing it

2019-04-06 04:54 UTC, merged