Faction spawners didn't work, but now they do!
Persistent-SS13/Persistent-Bay pull request #1130
Opened 2019-04-05 19:59 UTC by PsyCommando

* Used lazy macros to handle dealing with the faction list.
* Fixed the faction spawners deleting themselves before spawning the actual faction.

2019-04-06 01:29 UTC, Andrew-Fall requested changes

2019-04-06 01:29 UTC, Andrew-Fall commented on code/modules/factions/bluespace_satellite.dm
> +		LAZYADD(GLOB.all_world_factions, new_faction)
Shouldn't these be LAZYDISTINCTADD?

2019-04-06 07:41 UTC, PsyCommando commented on code/modules/factions/bluespace_satellite.dm
> +		LAZYADD(GLOB.all_world_factions, new_faction)
I guess it could be. Its not like the list is associative or that theres a chance for newly made factions to be duplicates though. since its a simple array.

2019-04-06 17:16 UTC, Andrew-Fall requested changes

2019-04-06 17:16 UTC, Andrew-Fall commented on code/modules/factions/faction.dm
> +	qdel_self()
Should be return INITIALIZE_HINT_QDEL

2019-04-06 23:59 UTC, PsyCommando commented on code/modules/factions/faction.dm
> +	qdel_self()
True

2019-04-07 00:46 UTC, Andrew-Fall approved these changes
Seems fine and passes Travis

2019-04-07 00:46 UTC, merged