Discord API and Bot for PSS13 (EMAIL NOTIFICATIONS)
Persistent-SS13/Persistent-Bay pull request #1136
Opened 2019-04-27 14:54 UTC by ingles98

Adds a very neaty API for all your in-game to Discord needs!

Comes with a working link/unlink and mailing notification system PLUS a working bot for discord.

Has a lot of potential features in the future!

2019-04-29 21:40 UTC, Andrew-Fall requested changes

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +var/global/datum/discord_api/discord_api = new()
GLOBAL_DATUM_INIT(discord_api, /datum/discord_api, new)

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +	if (g.Execute(discord_api.db) && g.NextRow())
Shouldn't these be this object's variables, and therefore only require ...FROM [usersTable] WHERE... and ...g.Execute(db)...

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +		discord_api.send_message("BROADCAST|[msg]")
GLOB.discord_api.send_message...

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +		if (g.Execute(discord_api.db) && g.NextRow())
...FROM [GLOB.discord_api.userTable]...
...(GLOB.discord_api.db)...

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +			if(!q.Execute(discord_api.db))
...INTO [GLOB.discord_api.usersTable]...
...(GLOB.discord_api.db)...

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/discord_persistence/_hook.dm
> +		if (delete.Execute(discord_api.db))
GLOBS

2019-04-29 21:40 UTC, Andrew-Fall commented on code/modules/modular_computers/NTNet/emails/email_account.dm
> +	discord_api.mail(src.login, received_message)
GLOB.discord_api.mail...

2019-04-30 07:10 UTC, ingles98 commented on code/modules/discord_persistence/_hook.dm
> +	if (g.Execute(discord_api.db) && g.NextRow())
What do u mean? Well i am fairly amateur in Db code, but i do think i need the select cmd

2019-04-30 19:44 UTC, ingles98 commented on code/modules/discord_persistence/_hook.dm
> +	if (g.Execute(discord_api.db) && g.NextRow())
Oh lmao i know what u mean now. Couldn't get it through my phone somehow. Yes you're right, i think that happened when i was using find/replace in some cases.

2019-05-01 03:54 UTC, merged