Bug fiesta
Persistent-SS13/Persistent-Bay pull request #1198
Opened 2019-06-24 19:08 UTC by PsyCommando

A large collection of bug and runtimes fixes
* Fix many wrongly assigned icon for clothing

2019-06-26 01:50 UTC, Andrew-Fall requested changes

2019-06-26 01:50 UTC, Andrew-Fall commented on code/controllers/employment_controller.dm
>  	if(payday)
Pretty sure this is an issue with tabbing below, where people themselves are payed

2019-06-26 01:50 UTC, Andrew-Fall commented on code/controllers/master.dm
> +		if(player && player.ready && player.mind)
We call player.new_player_panel(). Why check for player?

2019-06-26 01:50 UTC, Andrew-Fall commented on code/controllers/subsystems/initialization/character_setup.dm
> +		wait = 1 SECOND
Might be better to put this in fire, such that once all are initialized, wait goes up to 1 second. This way it rapidly fires as much as it needs at the start.

2019-06-26 01:50 UTC, Andrew-Fall commented on code/game/machinery/cryopod.dm
> -	LAZYADD(component_parts, new /obj/item/weapon/stock_parts/console_screen(src))
Was this and the other removals of part addition handled somewhere else?

2019-06-26 01:50 UTC, Andrew-Fall commented on code/modules/construction/girderparts.dm
> -	name = "[material.display_name] " + initial(name)
Why was this removed?

2019-06-26 01:50 UTC, Andrew-Fall commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
Change this to a standard var/global/list/all_world_factions = list()

2019-06-26 02:18 UTC, PsyCommando commented on code/controllers/employment_controller.dm
>  	if(payday)
Brawler told me to move it there so the game would compile

2019-06-26 18:41 UTC, Andrew-Fall commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
Test

2019-06-26 21:34 UTC, Andrew-Fall submitted a review, later dismissed

2019-06-26 21:34 UTC, Andrew-Fall reviewed
Github why you no work

2019-06-26 21:41 UTC, Andrew-Fall requested changes

2019-06-26 21:41 UTC, Andrew-Fall commented on code/controllers/master.dm
> +		if(player && player.ready && player.mind)
No need for if(player ...) as player will not be null

2019-06-26 21:41 UTC, Andrew-Fall commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
There is a better way to do this I believe. I'll look it up

2019-06-27 05:12 UTC, PsyCommando commented on code/controllers/master.dm
> +		if(player && player.ready && player.mind)
Yeah, but I only un-indented this so it wasn't all under the if and wouldn't run at all.

2019-06-27 05:13 UTC, PsyCommando commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
Yeah, writing a SSfaction of some sort. But I don't really have the time or will to go that far XD And we got enough bugs already ^^;

2019-06-27 16:48 UTC, Andrew-Fall commented
## UNIT_TEST ##: [UNIQUENESS: Research Designs Shall Be Unique]: Build Paths - /obj/item/weapon/circuitboard/optable - The following entries have the same value: /datum/design/circuit/operatingtable and /datum/design/circuit/operating_table

2019-06-27 16:53 UTC, Andrew-Fall commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
Global Unmanaged doesn't work like that. In the define it's set to the values used in the macro. Use GLOBAL_RAW_VAR(blah...) = list() instead

2019-06-27 19:04 UTC, PsyCommando commented on code/modules/factions/faction.dm
> +GLOBAL_RAW(/list/datum/world_faction/all_world_factions); GLOBAL_UNMANAGED(X, InitValue); //Don't init as empty list, because it happens too late during init
`#define GLOBAL_UNMANAGED(X, InitValue) /datum/controller/global_vars/proc/InitGlobal##X()
`
Well, it seems like it defines an empty proc. Also, I don't actually need/want it initialized, because I want it lazy accessed.

2019-06-27 20:34 UTC, merged

2019-06-27 20:59 UTC, PsyCommando commented
I'll make another one for removing the duplicate I guess