Cryo_crate Patch 1
Persistent-SS13/Persistent-Bay pull request #1212
Opened 2019-06-27 01:58 UTC by Viole7

*Changes crates to only spawn the contents upon opening.
*Possible fix to icon issues.
*Unsealed crates located on inactive z-levels delete after some time.
*Minor improvements and alterations.

2019-06-27 04:01 UTC, Andrew-Fall requested changes

2019-06-27 04:01 UTC, Andrew-Fall commented on code/game/objects/structures/crates_lockers/closets/cryo_crate.dm
> +
There's 4 spaces in a row in this area instead of a tab

2019-06-27 04:04 UTC, Viole7 commented on code/game/objects/structures/crates_lockers/closets/cryo_crate.dm
> +
No clue how that got there, thanks for spotting it.

2019-06-27 05:19 UTC, PsyCommando commented
@Viole7 Just wondering, but can we find bees for bee hives in those crates?

2019-06-27 07:05 UTC, Viole7 commented
> 
> 
> @Viole7 Just wondering, but can we find bees for bee hives in those crates?

Not currently, but I don't see why they couldn't be added. I'll add them tomorrow along with some minor changes I want to make.

2019-06-28 00:47 UTC, PsyCommando approved these changes
Looks good to me! Appearence probably won't work, but we really need this change for tomorrow.

2019-06-28 01:14 UTC, Viole7 commented
> 
> 
> Looks good to me! Appearence probably won't work, but we really need this change for tomorrow.

I tried creating an entry in the appearance datum, the closed state worked fine but for some reason the open state wouldn't display. I used VV verify the state was being assigned correctly, manually setting the icon var caused it to display properly. This despite both states residing in the same .dmi file, so it shouldn't have mattered. Not exactly sure what was going on. I saw that other objects were setting closet_appearance to null and manually assigning the icons, so I went with that. Is it the server saving that's assigning the icon to the default in the appearance datum? If so, what exactly is doing that? I've never actually setup my test server to save, so I've only been testing this stuff without saves.

2019-06-28 01:29 UTC, merged