Egg reduction and half chicken meat
Persistent-SS13/Persistent-Bay pull request #1278
Opened 2019-07-04 02:11 UTC by HbsRed

2019-07-04 02:12 UTC, Andrew-Fall commented on code/modules/mining/mine_items.dm
> +//obj/item/weapon/pickaxe/hammer
Thought Brawler fixed this

2019-07-04 02:14 UTC, Andrew-Fall requested changes

2019-07-04 02:14 UTC, Andrew-Fall commented on code/modules/mining/mine_items.dm
> +//obj/item/weapon/pickaxe/hammer
This isn't using the /* */

2019-07-04 02:17 UTC, Andrew-Fall approved these changes
Code checks out, waiting for Travis to be updated.

2019-07-04 03:26 UTC, PsyCommando commented
Its the dev branch again though

2019-07-05 00:34 UTC, PsyCommando commented
Dude, you're pushing more unrelated changes into your pr right now.. You really need to make a branch for your feature changes ^^;

2019-07-05 00:59 UTC, PsyCommando commented on code/game/machinery/seed_extractor.dm
> +				var/produce =(1)
The problem with nerfing things this way is that starting player are enormously disadvantaged since they don't have much seeds to waste, and will get seedless at one point from plants dying, and bugs, pest, weeds, etc..
I'd suggest reducing the default plants yield instead and maybe make some of them more finicky. And maybe changing the extracted seeds to rand(1,2). So that you're not inherently fucked by the RNG.

2019-07-05 14:25 UTC, merged

2019-07-05 23:44 UTC, rhicora commented on code/game/machinery/seed_extractor.dm
> +				var/produce =(1)
This is absolutely correct.