Materials
Persistent-SS13/Persistent-Bay pull request #1286
Opened 2019-07-04 21:44 UTC by Andrew-Fall

Closes #1284 
Closes #1234 
Closes #1235 
Closes #1232

2019-07-04 23:54 UTC, PsyCommando requested changes
Overall it looks really good! You've pretty much removed a lot of weird crud that accumulated in the stacks code. And I like what you did with the stacks constructor and saving the material name directly with read/write.

Only thing I'd really change maybe is the recalculation of the matter content for the stack inserted in the fabricator. 
And well, you probably want to add back the removed insert animation code.

2019-07-04 23:54 UTC, PsyCommando commented on code/modules/materials/recipes_stacks.dm
> +	spawn(0)
I'm not sure why you're using spawn here? Sounds like a bit of a patch.

2019-07-04 23:54 UTC, PsyCommando commented on code/modules/research/fabricator.dm
> +	var/stackMatter = stack.material.get_matter()
Normally it should be fine to just get the matter amount straight from the stack. Since stacks recalculate their amount of matter whenever something is added/removed so the calculation isn't duplicated everywhere and done over and over again externally.

2019-07-04 23:54 UTC, PsyCommando commented on code/modules/research/fabricator.dm
> -			if(metal_load_anim)
Seems like you forgot to recopy the insert animation code here.

2019-07-05 00:02 UTC, Andrew-Fall commented on code/modules/materials/recipes_stacks.dm
> +	spawn(0)
It is, for some reason it won't qdel correctly if the code continues. I messed around with it for a while before giving up and resorting to that

2019-07-05 00:04 UTC, Andrew-Fall commented on code/modules/research/fabricator.dm
> +	var/stackMatter = stack.material.get_matter()
I wanted the per-sheet matter to check if each sheet can fit. Some might have more then one material (aka reinforced materials)

2019-07-05 00:10 UTC, Andrew-Fall commented on code/modules/research/fabricator.dm
> -			if(metal_load_anim)
Readded

2019-07-05 00:29 UTC, PsyCommando commented on code/modules/research/fabricator.dm
> +	var/stackMatter = stack.material.get_matter()
Good call

2019-07-05 00:31 UTC, PsyCommando commented on code/modules/materials/recipes_stacks.dm
> +	spawn(0)
That's interesting, because we've been having lots of issues with the GC being an ass for a while now..

2019-07-05 00:31 UTC, PsyCommando approved these changes

2019-07-05 00:34 UTC, merged