More Raw Alcohol Recipes and 2 Jukebox Songs
Persistent-SS13/Persistent-Bay pull request #1310
Opened 2019-07-08 09:10 UTC by Koollan

Adds: Whiskey, Cognac, Vermouth, Gin, Tequila, Hessia (new alcohol), new Beer recipe and modifies other drink recipes. Adds Molasses as a reagent.

Also adds 2 jukebox .ogg files called Bluespace Ocean and This is Rain.

2019-07-08 12:01 UTC, ingles98 commented on code/modules/reagents/recipes/sodas.dm
>  	mix_message = "The frostoil and space cola mix together to form a thick liquid, as the fuel settles.. You thought you heard the air breach alarm just now.."
change the 'space cola' accordingly i guess

2019-07-08 18:10 UTC, PsyCommando commented
this is going to break several recipes. and it adds duplicates too.

2019-07-08 19:03 UTC, PsyCommando requested changes
this pr is not gonna help us get rid of chem recipe conflicts and will add sevetal new ones. it also changes recipes we've had for a while for no good reason. honestly you should go back to the drawing board.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/molasses
this conflicts with honey crystalization.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/cognac
dont put new recipes randomly in this file. add them at the end or in the new recipe files. so your things dont get deleted by upstream merges

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +/datum/reagent/nutriment/molasses
move that to the bottom of the file please. Dont randomly slap it in the middle of everything.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(/datum/reagent/ethanol/wine = 1, /datum/reagent/ethanol/vodka = 1)
pretty sure this is gonna break some drink mixes.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/beer
there is already a beer recipe. and this conflict with the ale recipe.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/tequilla
That recipe needs more reagents or itll break things made from corn oil

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/whiskey
whiskey isnt made from molass only. Also there was already a whiskey recipe.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/starrycola
duplicate

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +datum/chemical_reaction/bluebird
duplicate

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/bj
duplicate

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +	name = "Calvin Craig"
duplicate

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/recipes/alcohol.dm
> +/* COMMENTED UNTIL NEW BREWING SYSTEM ADDED
dont comment out recipe while waiting on something.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/recipes/alcohol.dm
> +// SAME AS ABOVE
there is no reasons to comment out the recipes in this file only to splatter them into the master recipe file.

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/recipes/sodas.dm
> +	required_reagents = list(/datum/reagent/drink/sodawater = 2, /datum/reagent/sugar = 4, /datum/reagent/nutriment/molasses = 1)
you're making a basic recipe too complicated and changed it for no good reasons

2019-07-08 19:03 UTC, PsyCommando commented on code/modules/reagents/recipes/sodas.dm
> +	required_reagents = list(/datum/reagent/drink/sodawater = 2, /datum/reagent/frostoil = 1) //helps keep your cool
theres a reason why this was made from spacecola. to keep coherency with the rest of the colas recipes without creating conflicts

2019-07-08 19:06 UTC, PsyCommando commented
you might want to make draft prs in the futuŕe if you're not sure about something

2019-07-08 19:24 UTC, Koollan commented on code/modules/reagents/recipes/sodas.dm
> +	required_reagents = list(/datum/reagent/drink/sodawater = 2, /datum/reagent/sugar = 4, /datum/reagent/nutriment/molasses = 1)
molasses is a lot easier to make than glycerol, and glycerol doesn't make much sense (it's a laxative, not a sweetener)

2019-07-08 19:25 UTC, Koollan commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/beer
both recipes still work respectively in my testing

2019-07-08 19:25 UTC, Koollan commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +/datum/reagent/nutriment/molasses
it's up near the top, where the nutriment class is.

2019-07-08 19:25 UTC, Koollan commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/cognac
they are grouped together with the other hard alcohols.

2019-07-08 19:26 UTC, Koollan commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/molasses
is that a new addition entirely? i was entirely unaware this existed

2019-07-08 19:27 UTC, Koollan commented on code/modules/reagents/recipes/sodas.dm
> +	required_reagents = list(/datum/reagent/drink/sodawater = 2, /datum/reagent/frostoil = 1) //helps keep your cool
there was no comment saying that, so i figured it was a mistake that all of the not-cola drinks were made from cola so i changed them all to soda to be more accurate.

2019-07-08 19:28 UTC, Koollan commented
apologies, i was just pretty sure about it all since in all of my testing, everything worked as intended and all of the 'conflicting' recipes also seemed to work so i'm just unsure of how to fix

2019-07-08 19:34 UTC, Koollan commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/tequilla
this was the old beer recipe, unchanged, so this already was broken.

2019-07-09 08:38 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/molasses
That's something rhicora added

2019-07-09 08:40 UTC, PsyCommando commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/cognac
Yeah, but it's making everyone's life harder to have those there instead of the other file.

2019-07-09 08:41 UTC, closed without merging