Autosave status
Persistent-SS13/Persistent-Bay pull request #1373
Opened 2019-07-31 03:05 UTC by HbsRed

2019-08-01 21:07 UTC, PsyCommando requested changes
You didn't compile this or even test it did you? :/

2019-08-01 21:07 UTC, PsyCommando commented on code/modules/mob/mob.dm
> +			stat("Autosave Timer"), SSautosave.time_next_save
The parenthesis at the end is missing. Also, that would display time in deciseconds, which would be a huge meaningless number to most people.

2019-08-02 04:17 UTC, HbsRed commented
See thing is.. i follow brawlers good ol advice and hes like yup sounds
great then sha bang. It no work pepe but you see what im trying to do yeah?

On Thu, Aug 1, 2019, 4:07 PM PsyCommando <notifications@github.com> wrote:

> *@PsyCommando* requested changes on this pull request.
>
> You didn't compile this or even test it did you? :/
> ------------------------------
>
> In code/modules/mob/mob.dm
> <https://github.com/Persistent-SS13/Persistent-Bay/pull/1373#discussion_r309897317>
> :
>
> > @@ -693,6 +693,7 @@
>  			stat("Local Time", stationtime2text())
>  			stat("Local Date", stationdate2text())
>  			stat("Server Uptime", roundduration2text())
> +			stat("Autosave Timer"), SSautosave.time_next_save
>
> The parenthesis at the end is missing. Also, that would display time in
> deciseconds, which would be a huge meaningless number to most people.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Persistent-SS13/Persistent-Bay/pull/1373?email_source=notifications&email_token=AKHBU7AZ35GMFDV22SULEFTQCNGB7A5CNFSM4IICATLKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCALAQ6A#pullrequestreview-269879416>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKHBU7FKVOMB375WNRT7MSDQCNGB7ANCNFSM4IICATLA>
> .
>

2019-08-06 20:17 UTC, PsyCommando commented
> 
> See thing is.. i follow brawlers good ol advice and hes like yup sounds great then sha bang. It no work pepe but you see what im trying to do yeah?
> […](#)
> On Thu, Aug 1, 2019, 4:07 PM PsyCommando ***@***.***> wrote: *@PsyCommando* requested changes on this pull request. You didn't compile this or even test it did you? :/ ------------------------------ In code/modules/mob/mob.dm <[#1373 (comment)](https://github.com/Persistent-SS13/Persistent-Bay/pull/1373#discussion_r309897317)> : > @@ -693,6 +693,7 @@ stat("Local Time", stationtime2text()) stat("Local Date", stationdate2text()) stat("Server Uptime", roundduration2text()) + stat("Autosave Timer"), SSautosave.time_next_save The parenthesis at the end is missing. Also, that would display time in deciseconds, which would be a huge meaningless number to most people. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <#1373?email_source=notifications&email_token=AKHBU7AZ35GMFDV22SULEFTQCNGB7A5CNFSM4IICATLKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCALAQ6A#pullrequestreview-269879416>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AKHBU7FKVOMB375WNRT7MSDQCNGB7ANCNFSM4IICATLA> .

Well I mean, my main concern is having the code work, so the server works XD Which is why I'm requesting changes on this pr so it can still work if this is merged XD

2019-09-06 20:56 UTC, PsyCommando commented
I guess I'll close this one, since you don't seem interested in fixing the PR.

2019-09-06 20:56 UTC, closed without merging