RE-Somi
Persistent-SS13/Persistent-Bay pull request #1421
Opened 2019-08-25 00:44 UTC by Draxtheros

New species, except not. This ports Resomi back into the code, with lore in the works for it's final inclusion.

2019-08-28 22:25 UTC, PsyCommando requested changes
Looks fine! 
Can you just add proper unit tests for the resomi too?

2019-08-28 22:25 UTC, PsyCommando commented on code/modules/species/species.dm
> +
Would be good to avoid commiting whitespace changes.

2019-08-29 20:16 UTC, Draxtheros commented
Typo in the unit tests fixed, as well as the extra white space

2019-08-29 20:26 UTC, PsyCommando approved these changes

2019-08-29 20:27 UTC, PsyCommando commented
Alright, looks good to me then!

2019-08-30 01:40 UTC, merged