Fixes Travis (somewhat)
Persistent-SS13/Persistent-Bay pull request #1423
Opened 2019-08-26 17:53 UTC by Bxil

2019-08-28 22:15 UTC, PsyCommando requested changes
Helps a bunch tbh!
Just re-comment the base nexus map, so we don't end up with weird issues on load, and it should be good.

2019-08-28 22:15 UTC, PsyCommando commented on maps/nexus/nexus.dm
> +	#include "nexus.dmm"
Can you re-comment that? Because of the way things work right now, we gotta keep the empty map on load, or it'll ovewrite stuff on load and create a lot of weirdness.

2019-08-30 08:04 UTC, Bxil commented on maps/nexus/nexus.dm
> +	#include "nexus.dmm"
A proper map like that is needed to be included. Around 80 of the unit test failures was caused by this.
With this we are down to one, and that one failure is legitimate.

2019-08-30 22:47 UTC, PsyCommando commented on maps/nexus/nexus.dm
> +	#include "nexus.dmm"
Its because brawler deleted the testing z-level on the "empty" version of the map. If you include this thing, there's gonna be way worst things than travis failing.

2019-09-01 13:30 UTC, Bxil commented on maps/nexus/nexus.dm
> +	#include "nexus.dmm"
Done.

2019-09-01 19:44 UTC, PsyCommando commented on maps/nexus/nexus.dm
> +	#include "nexus.dmm"
Ok!

2019-09-01 19:44 UTC, PsyCommando approved these changes

2019-09-01 19:45 UTC, PsyCommando commented
Hopefully the test z-level will get merged eventually too...

2019-09-17 09:19 UTC, merged