Research welder FIX
Persistent-SS13/Persistent-Bay pull request #1425
Opened 2019-08-27 23:55 UTC by fernandos13

Experimental welder research fix
 (damn phorosian thing got mixed up (well i hope thats not a problem since its the commit i did before and it was aceppted)

2019-08-29 23:32 UTC, PsyCommando requested changes
This needs to get cleaned up and sorted out. There's a bunch of things that don't have anything to do with welders, or change actual welder research requirements? And there's no explanation for anything in there.

2019-08-29 23:32 UTC, PsyCommando commented on code/modules/research/fabricators/engineering_fabricator.dm
> +
You removed the research required for the tank

2019-08-29 23:32 UTC, PsyCommando commented on code/modules/research/research.dm
> -	uses = 3
why did you remove this?

2019-08-29 23:32 UTC, PsyCommando commented on code/modules/research/fabricators/eva_fabricator.dm
> +
The softsuit stuff should probably be removed from this pr.

2019-08-30 02:23 UTC, fernandos13 commented on code/modules/research/research.dm
> +
here it is i just removed the uses = 3

2019-08-30 02:24 UTC, fernandos13 commented on code/modules/research/research.dm
> +
i thought that uses =  3 might be the thing blocking it. since thats the only reseach that dont work. and the only with such var

2019-08-30 02:25 UTC, fernandos13 commented on code/modules/research/fabricators/eva_fabricator.dm
> +
how do i remove it? without needing to recode that bit? and make a new PR? (cause the soft is aready in the dev)

2019-08-30 02:26 UTC, fernandos13 commented on code/modules/research/fabricators/engineering_fabricator.dm
> +
oh damn.. true lemme fix that one

2019-08-30 22:48 UTC, PsyCommando commented on code/modules/research/fabricators/eva_fabricator.dm
> +
You can revert individual files to their old version.

2019-10-04 23:51 UTC, PsyCommando requested changes
There's some strange removals being made in there

2019-10-04 23:51 UTC, PsyCommando commented on code/modules/research/fabricators/eva_fabricator.dm
> -
Why are you removing those?

2019-10-04 23:51 UTC, PsyCommando commented on code/modules/research/fabricators/eva_fabricator.dm
> -/datum/design/item/genfab/eva/modkit/phorosian
Why remove this?

2019-10-22 01:28 UTC, closed without merging