Resomi fixes
Persistent-SS13/Persistent-Bay pull request #1435
Opened 2019-09-01 03:26 UTC by Draxtheros

The language was not included, nor were names set up generate properly based on the species language. Additionally, some clothes that were missing their in-world icon have been fixed.

2019-09-01 19:13 UTC, PsyCommando requested changes
Looks good! Just add the other standard `available_cultural_info` for the other default tags. Because, the thing is very finicky, and it'll make it compatible with standard bay too.

2019-09-01 19:13 UTC, PsyCommando commented on code/modules/species/station/resomi.dm
> +	available_cultural_info = list(
I'd add the other basic tags too. Just in case. Because culture tags are super finicky.

2019-09-01 23:37 UTC, Draxtheros commented on code/modules/species/station/resomi.dm
> +	available_cultural_info = list(
It should be fine, the Human entry also only has the two, with the rest defaulting to whatever is in the base species.dm

2019-09-02 05:39 UTC, PsyCommando commented on code/modules/species/station/resomi.dm
> +	available_cultural_info = list(
Alright!

2019-09-02 05:39 UTC, PsyCommando approved these changes

2019-09-02 18:17 UTC, merged