Adjusts Guns
Persistent-SS13/Persistent-Bay pull request #894
Opened 2018-10-16 04:40 UTC by NataKilar

Energy weapons can no longer have their cells removed from their housing. Recharge them in the newly buildable recharger instead!

Fixes #842 
Fixes #834 
Fixes a bug in which cell rechargers would delete their cell upon deconstruction
Fixes a bug in which guns (both energy and ballistics) would have their loaded magazine or cell reset on load
Fixes a bug in which magazines and bullets would reset on load

2018-10-16 05:07 UTC, UndeadNappist commented
It's nice that you're adding rechargers, but I don't see the point in making energy cells non-removable, especially given the comparison to the current aspects of ballistics.

You're tackling a phantom problem that doesn't exist and probably won't, since the real issue is lack of prone mechanics and the overall high power of ballistics.

2018-10-16 05:17 UTC, PsyCommando commented
The bugfixes are fine, but I don't think we should make cells un-removable again. Its such an issue for energy weapons to need to be recharged instead of reloading them. It makes then unreliable in a pinch when there are many other ballistic alternative that offer a way to quickly and painlessly be reloaded. You don't want to be the one to run out of ammo in a firefight.

2018-10-16 05:19 UTC, NataKilar commented
A few things to note about this change. This is not intended to adjust the overall balance of energy weaponry,  and will likely leave them in the same state or slightly worse. The rationale behind this change is that the ability to remove power cells was intended solely as a method to recharge energy guns _at all_, and was not intended to make an "ammunition" like system for energy weapons.

If energy weapons are made re-loadable (they were not easily so previously, but others have stated their intent to generalize the energy gun cells) they become far more similar to ballistics. The end result will be that one type will always be better than the other, rather than fulfilling different niches. Thus, I believe that making this change will realign the purpose of energy weaponry in order to facilitate future balance changes. (If requested, I can move the cell removal stuff to a separate PR)

2018-10-16 05:39 UTC, NataKilar commented
Because some of these bug fixes are closely aligned with the removal of replaceable energy cells, I left it all in one PR. Since energy weapons are currently weak enough that they are barely used, and the "re-loadable lasers strategy" is probably used even less, I don't think this will have a major effect on balance.

2018-10-18 04:31 UTC, Andrew-Fall requested changes

2018-10-18 04:31 UTC, Andrew-Fall commented on code/game/machinery/recharger.dm
> +				break checking_allowed
This is seems overly complex, perhaps just check if it's disallowed first and return, then check if it's allowed.

2018-10-18 04:31 UTC, Andrew-Fall commented on code/modules/projectiles/ammunition.dm
> +			BB = new projectile_type(src)
I am fairly certain map_storage_loaded will only work in Initialize(), not New()

2018-10-18 04:31 UTC, Andrew-Fall commented on code/modules/projectiles/guns/projectile.dm
> +				ammo_magazine = new magazine_type(src)
Same as above, map_storage_loaded won't function in New(), only Initialize()

2018-10-18 16:44 UTC, NataKilar commented
Closing this, going to split it into two PRs

2018-10-18 16:44 UTC, closed without merging