Designer Update
Persistent-SS13/Persistent-Bay pull request #928
Opened 2018-10-20 14:14 UTC by ingles98

**WIP**

2018-12-04 15:26 UTC, Andrew-Fall requested changes

2018-12-04 15:26 UTC, Andrew-Fall commented on code/modules/designer/designer.dm
> +	usr << output("href='?src=\ref[src];[pixel_width];[pixel_height]","designer.browser:getData")
to_browser(user, output(...))

2018-12-04 15:26 UTC, Andrew-Fall commented on code/modules/designer/designer.dm
> +		usr << output("[title]","designer.browser:setTitle")
to_browser(user, output(...))

2018-12-04 15:26 UTC, Andrew-Fall commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
to_browser(user, output(...)) Also why is spawn needed for these?

2018-12-04 18:29 UTC, ingles98 commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
Simply the fact that it takes long in between the JS functions. Earlier versions i had problems with it as the order would get scrambled as some functions took more time than others, as they are called asyn it seems.
Havent tested with the newer approach. 

Also the multiple outputs are for multiple function calls with different arguments. I could indeed attempt a better implementation now as the code greatly diverged from what it was, but i only want to bother with it when i get the JSON string to be directly sent to DM

EDIT:
Oh yes i didnt know about the to_browser ss13 proc. Does it grant any benefit other than being friendlier?

2018-12-04 20:37 UTC, Andrew-Fall commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
Not really, it's pretty much for safety reasons. Keeps travis happy

2018-12-05 07:57 UTC, ingles98 commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
Dunno if its only on mobile but searching for 'To_browser' finds absolutely no reference

2018-12-16 18:52 UTC, PsyCommando commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
Can confirm, to_browser doesn't exist @Andrew-Fall

2019-01-23 14:10 UTC, ingles98 commented on code/modules/designer/designer.dm
> +		spawn(2) usr << output("[json_encode(pixel_list)]","designer.browser:getIconAsJSON")
I still haven't understood as to why Travis is mad about the PR.
"764 << uses (expecting exactly 762)" is the only thing I see pointing towards something off in code quality yet it doesn't tell me anything.

2019-02-22 16:22 UTC, merged